name: ci
on:
  push:
    branches:
      - 'main'
      - 'develop'
  pull_request:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.2
      - name: Run Test
        uses: cypress-io/github-action@v5
        with:
          component: true
